name: "Labels: Approved"
on:
  pull_request_review:
    types: [submitted]
jobs:
  add_label:
    # Change the repository name after you've made sure the team name is correct for your fork!
    if: ${{ (github.repository == 'for-forkonia') && (github.event.review.state == 'APPROVED') }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl  --silent --fail-with-body \
        -X DELETE \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{github.repository}}/issues/${{github.event.number}}/labels \
        -d '{'labels':['Status: Approved']}'"
    - if: "contains(github.event.pull_request.labels, 'Status: Untriaged')"
      run: |
        curl --silent --fail-with-body \
        -X DELETE \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ github.token }}" https://api.github.com/repos/${{ github.repository }}/issues/${{github.event.number}}/labels/Status%3A%20Untriaged
  
